# -*- coding: utf-8 -*-
"""Buku Logika Dasar Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16R_TWuUQxxV70rzN73UrP-PwfPqzsGYK

# Dasar Python

Berikut akan dijelaskan dasar-dasar Python.
 

*   **Judul Buku**: Logika Matematika untuk Analisis Algoritma
*   **Penulis**: Dr. Putu Harry Gunawan

**Hello world**
"""

print("Hello World")

"""**Variabel**"""

a= 1
b= 2
c= "Hello there"
print(a)
print(b)
print(c)

a = 10
b = 7
c = 10.24
d = 9.5
e = "text"

bulat = a + b
riil = c - d
kata = e + " manual"

print(bulat)
print(riil)
print(kata)

"""**Kondisi**"""

a = 10

if a<50:
  print("kurang 50")
elif a<100:
  print("kurang 100")
else:
  print("besar sama dengan 100")

"""**Perulangan**"""

i = 1
while i < 6:
  print(i)
  i += 1

for i in range(1,6):
  print(i)

"""**Larik**"""

Anggrek=["Macan", "Jamrud", "Ki Aksara"]
Genap = [2,4,6,8,10]

x = Anggrek[0]
print(x)

Anggrek[0]= "Bulan"

for x in Anggrek:
  print(x)

#menambah data
Genap.append(12)
print(Genap)
#menghilangan elemen ke-2
Genap.pop(1)
print(Genap)

"""**Fungsi**"""

def Salam(nama):
  print("Hallo "+ nama + " selamat datang")

Salam("Harry")
